#bootstrap:
#    assets:
#        - [source: vendor/twbs/bootstrap/dist/*/*, type: glob, filter: less]
#    filters:
#        - css_compressor

jquery:
    assets:
        - [source: vendor/yiisoft/jquery/jquery.min.js, type: file]