providers:
    service_controller: true
    url_generator: true
    session: true
    validator: true
    form: true
    translation: true
    http_cache: true
    serializer: false
    mail: false
    doctrine: false
    security: true
    remember_me: true
    twig: true
    http_fragment: true

user_providers:
    - '\Provider\SayHelloServiceProvider'