home:
    path: /
    defaults: { _controller: '\Controllers\DefaultController::indexAction', name: Silex }

hello:
    path: /hello/{name}
    defaults: { _controller: '\Controllers\DefaultController::indexAction', name: Silex }