home:
    path: /
    defaults: { _controller: '\Controller\DefaultController::indexAction', name: Silex }

footer:
    path: /footer
    defaults: { _controller: '\Controller\DefaultController::footerAction'}

form_test:
    path: /form
    defaults: { _controller: '\Controller\DefaultController::formAction' }
    methods:  [POST|GET]

login:
    path: /login
    defaults: { _controller: '\Controller\DefaultController::loginAction' }