home:
    path: /
    defaults: { _controller: '\Controller\DefaultController::indexAction'}

demo:
    path: /demo
    defaults: { _controller: '\Controller\DemoController::indexAction', name: Silex }

footer:
    path: /footer
    defaults: { _controller: '\Controller\DemoController::footerAction'}

form:
    path: /form
    defaults: { _controller: '\Controller\DemoController::formAction' }
    methods:  [POST|GET]

login:
    path: /login
    defaults: { _controller: '\Controller\DemoController::loginAction' }